# Copyright (c) 2011 Vincent Danjean <Vincent.Danjean@imag.fr>
#
# This is part of a GNU-Makefile

# This makefile will compile the flavor named as the current directory
# This compilation is done *WITHOUT* -DCHANGED (look into the build/
# directory to have a build with -DCHANGED)

FLAVOR=$(notdir $(CURDIR))

ifneq ($(MAKECMDGOALS),clean)
$(warning Compiling a nachos kernel *without* user modifications (without -DCHANGED))
endif

include ../Makefile.common
include ../Makefile.compile-flavor
