# This Makefile (cross-)compiles Nachos MIPS user programs
#
# In this directory, compilation is done *WITHOUT* -DCHANGED
# Use the build/ directory to build these programs with -DCHANGED
#
# By default, all C files are expected to create a program.
# If this is not the case, change rules/depends in Makefile.compile-mips-progs

TARGET=MIPS
include ../Makefile.common
include $(topsrc_dir)/Makefile.compile-mips-progs

