# NOTE: this is a GNU Makefile.  You must use "gmake" rather than "make".
#
# Makefile for the threads assignment.  The threads assignment must
#    be done first!
#
# Copyright (c) 1992 The Regents of the University of California.
# All rights reserved.  See copyright.h for copyright notice and limitation 
# of liability and disclaimer of warranty provisions.

# This makefile will compile the flavor named as the current directory
# This compilation is done *WITHOUT* -DCHANGED (look into the build/
# directory to have a build with -DCHANGED)

include ../Makefile.compile-initial-nachos

