# Copyright (C) 2011 Vincent Danjean <Vincent.Danjean@imag.fr>
#
# This Makefile try to recompile the original nachos *without* -DCHANGED
#
# If "#ifdef CHANGED" is corretly used, this directory should always compile.

AUTOLOAD_USERPROGS=$(ORIG_USERPROGS)
AUTOLOAD_KERNELS=$(ORIG_FLAVORS)

include ../Makefile.rules-nachos

